CREATE TABLE ma."CUSTOMER"
(
    "ID" INTEGER NOT NULL PRIMARY KEY,
    "NAME" VARCHAR,
	"FIRSTNAME" VARCHAR,
	"ADDRESS_1" VARCHAR,
    "ADDRESS_2" VARCHAR,
    "POSTALCODE" VARCHAR,
    "CITY" VARCHAR,
    "COUNTRY" VARCHAR,
    "PHONE" VARCHAR,
    "EMAIL" VARCHAR,
    "CIVILITY" VARCHAR,
    "NATIONALITY" VARCHAR,
    "PASSPORTNUMBER" VARCHAR,
    "ISSUEDATE" DATE,
    "EXPIRATIONDATE" DATE
);
