CREATE TABLE ma."CLIENT"
(
    "ID" INTEGER NOT NULL PRIMARY KEY,
    "NOM" VARCHAR,
	"PRENOM" VARCHAR,
	"ADRESSE_1" VARCHAR,
    "ADRESSE_2" VARCHAR,
    "CODEPOSTAL" VARCHAR,
    "VILLE" VARCHAR,
    "PAYS" VARCHAR,
    "TELEPHONE" VARCHAR,
    "EMAIL" VARCHAR,
    "CIVILITE" VARCHAR,
    "NATIONALLITE" VARCHAR,
    "NUMEROPASSEPORT" VARCHAR,
    "DATEEMISSION" DATE,
    "DATEEXPIRATION" DATE

);
