CREATE TABLE ma."PROGRAMME"
(
    "ID" INTEGER NOT NULL PRIMARY KEY,
    "IDCATEGORIE" INTEGER NOT NULL,
    "NOM" VARCHAR NOT NULL,
    "NOMCOMPLET" VARCHAR,
	"THEME" VARCHAR,
    "DATEDEBUT" DATE,
    "DATEFIN" DATE,
    "LIEU" VARCHAR,
    "TARIF" VARCHAR
);
