CREATE TABLE ma."COORDONNEESBANCAIRES"
(
    "ID" INTEGER NOT NULL PRIMARY KEY,
    "IDCLIENT" INTEGER NOT NULL,
	"NOMCARTE" VARCHAR,
    "NUMEROCARTE" INTEGER NOT NULL,
    "DATEEXPIRATION" DATE NOT NULL,
    "CODECVC" INTEGER NOT NULL,
    "TYPECARTE" VARCHAR
);
