CREATE TABLE ma."PROGRAM"
(
    "ID" INTEGER NOT NULL PRIMARY KEY,
    "IDCATEGORY" INTEGER NOT NULL,
    "NAME" VARCHAR NOT NULL,
    "FULLNAME" VARCHAR,
	"THEME" VARCHAR,
    "STARTDATE" DATE,
    "ENDDATE" DATE,
    "PLACE" VARCHAR
);
